# Generated by Django 5.1.3 on 2024-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='jwt_auth.userinfo'),
        ),
    ]
