# Generated by Django 5.1.3 on 2024-12-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_userinfo_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='following',
        ),
    ]
