# Generated by Django 5.1.3 on 2024-12-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_userinfo_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
