# Generated by Django 5.1.3 on 2024-12-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
