import './globals.css';
import '@/styles/style.css';
import '@/styles/custom.css';
import 'react-perfect-scrollbar/dist/css/styles.css';

import { Suspense } from 'react';
// import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import DefaultLayout from '@/components/templates/DefaultLayout';
import localFont from 'next/font/local'
import { Noto_Sans_JP } from 'next/font/google';

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Specify desired weights
  display: 'swap', // Use font-display: swap for better performance
});
 
// Font files can be colocated inside of `app`
export const font_genjyuu_bold = localFont({
  src: './fonts/GenJyuuGothicX-Bold.ttf',
  weight: '100 900'
})

export const font_genjyuu_regular = localFont({
    src: './fonts/GenJyuuGothicX-Regular.ttf',
    weight: '100 900'
  })

// export const metadata: Metadata = {
//     title: 'Tokyo Stock News',
//     description: 'Generated by create next app'
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <head>
                <Suspense>
                    <meta name='keywords' content='' />
                </Suspense>

                <link href='https://fonts.googleapis.com/earlyaccess/notosansjapanese.css' rel='stylesheet' />
                <link href='https://fonts.googleapis.com/css?family=Kosugi' rel='stylesheet' />
            </head>
            <DefaultLayout>
                <div className={notoSansJP.className}>
                    {children}
                    <Analytics />
                </div>
            </DefaultLayout>
        </html>
    );
}
