# Generated by Django 5.1.3 on 2024-12-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0002_category_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
