# Generated by Django 5.1.3 on 2024-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_schema', '0003_article_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
